// Code generated by rlpgen. DO NOT EDIT.

//go:build !norlpgen
// +build !norlpgen

package types

import (
	"io"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/rlp"
)

func (obj *FutureProposal) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	_tmp1 := w.List()
	for _, hash := range obj.TxHashes {
		w.WriteBytes(hash[:])
	}
	w.ListEnd(_tmp1)
	w.WriteBytes(obj.Signature)
	w.ListEnd(_tmp0)
	return w.Flush()
}

// decFutureProposal is an intermediate struct used to decode FutureProposal via
// standard RLP reflection, ensuring the decoder matches EncodeRLP exactly.
type decFutureProposal struct {
	TxHashes  []common.Hash
	Signature []byte
}

func (obj *FutureProposal) DecodeRLP(s *rlp.Stream) error {
	var dec decFutureProposal
	if err := s.Decode(&dec); err != nil {
		return err
	}
	obj.TxHashes = dec.TxHashes
	obj.Signature = dec.Signature
	return nil
}
