// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

// MarshalJSON marshals as JSON.
func (f FutureProposal) MarshalJSON() ([]byte, error) {
	type FutureProposal struct {
		TxHashes  []common.Hash `json:"txHashes"`
		Signature hexutil.Bytes `json:"signature"`
	}
	var enc FutureProposal
	enc.TxHashes = f.TxHashes
	enc.Signature = hexutil.Bytes(f.Signature)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (f *FutureProposal) UnmarshalJSON(input []byte) error {
	type FutureProposal struct {
		TxHashes  []common.Hash  `json:"txHashes"`
		Signature *hexutil.Bytes `json:"signature"`
	}
	var dec FutureProposal
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.TxHashes != nil {
		f.TxHashes = dec.TxHashes
	}
	if dec.Signature != nil {
		f.Signature = *dec.Signature
	}
	return nil
}
