// Code generated by rlpgen. DO NOT EDIT.

//go:build !norlpgen
// +build !norlpgen

package types

import (
	"io"

	"github.com/ethereum/go-ethereum/rlp"
)

func (obj *FutureProposal) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	_tmp1 := w.List()
	for _, hash := range obj.TxHashes {
		w.WriteBytes(hash[:])
	}
	w.ListEnd(_tmp1)
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.Signature)
	w.ListEnd(_tmp0)
	return w.Flush()
}
